### ISSUE TITLE
Ios title localization error 

### ISSUE THREAD

**Issue by aungaung001** [pushy/pushy-flutter#81]
ios is getting json title in notificaiton list 

how can i handle this

     Pushy.notify(  langCode == "eng"
            ? data['title']['en']
            : data['title']['mm'],  langCode == "eng"
            ? data['description']['en']
            : data['description']['mm'], data);

**Comment by pushy** [comment]
Hi @aungaung001,
Thanks for reaching out. We'd be glad to assist with your inquiry.

To localize the notification title on iOS, please specify the `notification.title_loc_key` parameter of the [Send Notifications API](https://pushy.me/docs/api/send-notifications).

**`notification.title_loc_key`**: The localization key of a string present in your app's `Localizable.strings` file. Use this parameter to localize the notification title. Refer to the [APNs documentation](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html#//apple_ref/doc/uid/TP40008194-CH10-SW9) for more information.

Please let us know if there's anything else we can help with.

**Comment by aungaung001** [comment]
How can i disable auto pushing notification 
i want to disable and push noti with local push noti 
how can i handle this
I don't want to edit this push notiticaion Backend

**Comment by pushy** [comment]
Hi @aungaung001,
For sending notifications on iOS, the notification title and body must be set by the backend server, unlike on Android. This is simply how the APNs push notification system is implemented, as by default your app will not get woken up to process the notification in the background. 

The notification gets displayed by iOS to the user automatically, and that's why the title/body must be set by your backend.
